"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Edit3, Eye, Search, Trash2 } from "lucide-react";
import { COUNSELLORS, LEAD_SOURCES, LEAD_STATUSES, COURSES, STATUS_COLORS } from "@/lib/constants";
import { apiFetch, responseMessage } from "@/lib/client-api";
import type { LeadRecord } from "@/lib/types";
import { Badge, Button, EmptyState, InputField, SelectField } from "./ui";
import { formatDate } from "@/lib/constants";

export function LeadTable() {
  const [leads, setLeads] = useState<LeadRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [source, setSource] = useState(""); const [course, setCourse] = useState(""); const [counsellor, setCounsellor] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); if (source) params.set("leadSource", source); if (course) params.set("course", course); if (counsellor) params.set("assignedCounsellor", counsellor); try { const body = await responseMessage(await apiFetch(`/api/leads?${params}`)); setLeads(body.leads); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load leads."); } finally { setLoading(false); } }, [course, counsellor, search, source, status]);
  useEffect(() => { const timer = window.setTimeout(load, 180); return () => window.clearTimeout(timer); }, [load]);
  const remove = async (lead: LeadRecord) => { if (!window.confirm(`Delete ${lead.name}?`)) return; try { await responseMessage(await apiFetch(`/api/leads/${lead.id}`, { method: "DELETE" })); setLeads((current) => current.filter((item) => item.id !== lead.id)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to delete lead."); } };
  return <div className="panel table-panel"><div className="filter-bar"><div className="filter-search"><label><span className="field-label">Search name, phone, or email</span><div style={{ position: "relative" }}><Search size={15} className="muted" style={{ position: "absolute", left: 11, top: 12 }} /><input className="input" style={{ paddingLeft: 34 }} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search leads..." /></div></label></div><div className="filter-item"><SelectField label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{LEAD_STATUSES.map((value) => <option key={value}>{value}</option>)}</SelectField></div><div className="filter-item"><SelectField label="Source" value={source} onChange={(event) => setSource(event.target.value)}><option value="">All sources</option>{LEAD_SOURCES.map((value) => <option key={value}>{value}</option>)}</SelectField></div><div className="filter-item"><SelectField label="Course" value={course} onChange={(event) => setCourse(event.target.value)}><option value="">All courses</option>{COURSES.map((value) => <option key={value}>{value}</option>)}</SelectField></div><div className="filter-item"><SelectField label="Counsellor" value={counsellor} onChange={(event) => setCounsellor(event.target.value)}><option value="">All counsellors</option>{COUNSELLORS.map((value) => <option key={value}>{value}</option>)}</SelectField></div></div>{error && <div className="alert" style={{ margin: 16 }}>{error}</div>}{loading ? <div className="empty">Loading leads...</div> : !leads.length ? <EmptyState message="No leads match these filters." /> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Course</th><th>Source</th><th>Status</th><th>Counsellor</th><th>Next follow-up</th><th>Age</th><th /></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id}><td><Link href={`/leads/${lead.id}`} className="lead-name">{lead.name}</Link><div className="muted small">{lead.email || "No email"}</div></td><td>{lead.phone}</td><td>{lead.course}</td><td>{lead.leadSource}</td><td><Badge tone={STATUS_COLORS[lead.status]}>{lead.status}</Badge></td><td>{lead.assignedCounsellor}</td><td>{formatDate(lead.nextFollowUpDate)}</td><td><Badge tone={lead.ageTone}>{lead.ageDays}d - {lead.ageCategory}</Badge></td><td><div className="row-actions"><Link href={`/leads/${lead.id}`} className="button ghost icon" title="View"><Eye size={15} /></Link><Link href={`/leads/${lead.id}/edit`} className="button ghost icon" title="Edit"><Edit3 size={15} /></Link><Button variant="ghost" className="icon" title="Delete" onClick={() => remove(lead)}><Trash2 size={15} /></Button></div></td></tr>)}</tbody></table></div>}</div>;
}
